AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB table for Country Reference Service'

Parameters:
  TableName:
    Type: String
    Default: Countries
    Description: Name of the DynamoDB table

Resources:
  CountriesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: alpha2Code
          AttributeType: S
        - AttributeName: createDate
          AttributeType: S
        - AttributeName: alpha3Code
          AttributeType: S
        - AttributeName: numericCode
          AttributeType: S
      KeySchema:
        - AttributeName: alpha2Code
          KeyType: HASH
        - AttributeName: createDate
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI-Alpha3
          KeySchema:
            - AttributeName: alpha3Code
              KeyType: HASH
            - AttributeName: createDate
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI-Numeric
          KeySchema:
            - AttributeName: numericCode
              KeyType: HASH
            - AttributeName: createDate
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Service
          Value: country-service
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  TableName:
    Description: Name of the DynamoDB table
    Value: !Ref CountriesTable
    Export:
      Name: !Sub '${AWS::StackName}-TableName'

  TableArn:
    Description: ARN of the DynamoDB table
    Value: !GetAtt CountriesTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-TableArn'

