AWSTemplateFormatVersion: '2010-09-09'
Description: 'GitHub Actions deployment roles for Country Reference Service'

Parameters:
  GitHubOrg:
    Type: String
    Description: GitHub organization or username (e.g., edoatley)
  GitHubRepo:
    Type: String
    Description: GitHub repository name (e.g., country-api)
  OIDCProviderArn:
    Type: String
    Description: ARN of the OIDC provider for GitHub Actions (e.g., arn:aws:iam::ACCOUNT_ID:oidc-provider/token.actions.githubusercontent.com)
  LambdaExecutionRoleArnStaging:
    Type: String
    Description: ARN of the Lambda execution role for staging (from lambda-execution-roles stack)
    Default: ''
  LambdaExecutionRoleArnProduction:
    Type: String
    Description: ARN of the Lambda execution role for production (from lambda-execution-roles stack)
    Default: ''

Resources:

  # Staging Deployment Role
  GitHubActionsDeployStagingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GitHubActions-Deploy-Staging
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref OIDCProviderArn
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub:
                  - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:ref:refs/heads/main'
                  - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:ref:refs/tags/v*'
      Policies:
        - PolicyName: LambdaDeploymentPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:CreateFunction
                  - lambda:UpdateFunctionCode
                  - lambda:UpdateFunctionConfiguration
                  - lambda:GetFunction
                  - lambda:GetFunctionConfiguration
                Resource: !Sub 'arn:aws:lambda:*:${AWS::AccountId}:function:country-service-lambda-staging'
              - Effect: Allow
                Action:
                  - lambda:ListFunctions
                Resource: '*'
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource:
                  - !If
                    - HasStagingRoleArn
                    - !Ref LambdaExecutionRoleArnStaging
                    - !Sub 'arn:aws:iam::${AWS::AccountId}:role/country-service-lambda-execution-staging'
                  - !If
                    - HasProductionRoleArn
                    - !Ref LambdaExecutionRoleArnProduction
                    - !Sub 'arn:aws:iam::${AWS::AccountId}:role/country-service-lambda-execution-production'
              - Effect: Allow
                Action:
                  - iam:GetRole
                Resource:
                  - !If
                    - HasStagingRoleArn
                    - !Ref LambdaExecutionRoleArnStaging
                    - !Sub 'arn:aws:iam::${AWS::AccountId}:role/country-service-lambda-execution-staging'
                  - !If
                    - HasProductionRoleArn
                    - !Ref LambdaExecutionRoleArnProduction
                    - !Sub 'arn:aws:iam::${AWS::AccountId}:role/country-service-lambda-execution-production'
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackOutputs
                Resource: !Sub 'arn:aws:cloudformation:*:${AWS::AccountId}:stack/country-service-lambda-execution-roles/*'
              - Effect: Allow
                Action:
                  - sts:GetCallerIdentity
                Resource: '*'
      Tags:
        - Key: Environment
          Value: staging
        - Key: Service
          Value: country-service
        - Key: ManagedBy
          Value: CloudFormation

  # Production Deployment Role
  GitHubActionsDeployProductionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GitHubActions-Deploy-Production
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref OIDCProviderArn
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
                token.actions.githubusercontent.com:sub: !Sub 'repo:${GitHubOrg}/${GitHubRepo}:workflow:Deploy'
      Policies:
        - PolicyName: LambdaDeploymentPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:CreateFunction
                  - lambda:UpdateFunctionCode
                  - lambda:UpdateFunctionConfiguration
                  - lambda:GetFunction
                  - lambda:GetFunctionConfiguration
                Resource: !Sub 'arn:aws:lambda:*:${AWS::AccountId}:function:country-service-lambda-production'
              - Effect: Allow
                Action:
                  - lambda:ListFunctions
                Resource: '*'
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource:
                  - !If
                    - HasStagingRoleArn
                    - !Ref LambdaExecutionRoleArnStaging
                    - !Sub 'arn:aws:iam::${AWS::AccountId}:role/country-service-lambda-execution-staging'
                  - !If
                    - HasProductionRoleArn
                    - !Ref LambdaExecutionRoleArnProduction
                    - !Sub 'arn:aws:iam::${AWS::AccountId}:role/country-service-lambda-execution-production'
              - Effect: Allow
                Action:
                  - iam:GetRole
                Resource:
                  - !If
                    - HasStagingRoleArn
                    - !Ref LambdaExecutionRoleArnStaging
                    - !Sub 'arn:aws:iam::${AWS::AccountId}:role/country-service-lambda-execution-staging'
                  - !If
                    - HasProductionRoleArn
                    - !Ref LambdaExecutionRoleArnProduction
                    - !Sub 'arn:aws:iam::${AWS::AccountId}:role/country-service-lambda-execution-production'
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackOutputs
                Resource: !Sub 'arn:aws:cloudformation:*:${AWS::AccountId}:stack/country-service-lambda-execution-roles/*'
              - Effect: Allow
                Action:
                  - sts:GetCallerIdentity
                Resource: '*'
      Tags:
        - Key: Environment
          Value: production
        - Key: Service
          Value: country-service
        - Key: ManagedBy
          Value: CloudFormation

Conditions:
  HasStagingRoleArn: !Not [!Equals [!Ref LambdaExecutionRoleArnStaging, '']]
  HasProductionRoleArn: !Not [!Equals [!Ref LambdaExecutionRoleArnProduction, '']]

Outputs:
  GitHubActionsRoleArnStaging:
    Description: ARN of the GitHub Actions deployment role for staging
    Value: !GetAtt GitHubActionsDeployStagingRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-GitHubActionsRoleArnStaging'

  GitHubActionsRoleArnProduction:
    Description: ARN of the GitHub Actions deployment role for production
    Value: !GetAtt GitHubActionsDeployProductionRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-GitHubActionsRoleArnProduction'

  OIDCProviderArn:
    Description: ARN of the OIDC provider
    Value: !Ref OIDCProviderArn

