AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lambda function for Country Reference Service'

Parameters:
  Environment:
    Type: String
    Description: Environment name (staging or production)
    AllowedValues:
      - staging
      - production
  LambdaExecutionRoleArn:
    Type: String
    Description: ARN of the Lambda execution role
  CodeS3Bucket:
    Type: String
    Description: S3 bucket containing the Lambda deployment package
  CodeS3Key:
    Type: String
    Description: S3 key of the Lambda deployment package
  ApiKey:
    Type: String
    Description: API key for authentication
    NoEcho: true
  DynamoDBTableName:
    Type: String
    Default: Countries
    Description: DynamoDB table name
  Timeout:
    Type: Number
    Default: 30
    Description: Lambda function timeout in seconds
  MemorySize:
    Type: Number
    Default: 512
    Description: Lambda function memory size in MB

Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'country-service-lambda-${Environment}'
      Runtime: java21
      Role: !Ref LambdaExecutionRoleArn
      Handler: com.example.country.adapters.lambda.LambdaEntryPoint::handleRequest
      Code:
        S3Bucket: !Ref CodeS3Bucket
        S3Key: !Ref CodeS3Key
      Timeout: !Ref Timeout
      MemorySize: !Ref MemorySize
      Architectures:
        - x86_64
      Environment:
        Variables:
          API_KEY: !Ref ApiKey
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTableName
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: country-service
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaFunctionArn'

  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref LambdaFunction
    Export:
      Name: !Sub '${AWS::StackName}-LambdaFunctionName'

